version: '3'

services:
  db:
    image: mysql:8.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: generatepdf
    volumes:
      - ./mysql_data:/var/lib/mysql